.prettierrc.js
=>  Fix prettier config

.github/workflows/docs.yml
- Those who contributed to this PR.
=> ci(docs publish): assert yarn pm

CONTRIBUTING.md, README.md
=> fix(docs): readme contributor agreement link

.github/workflows/release.yml
- the docs site no longer has a docker image
=> ci(release): only build web docker image

apps/web/.env.example, turbo.json
- fix misc issues with env vars
=> fix env vars

.github/workflows/scanning.yml
- add code scanning like rican wanted
=> ci(code scanning): added codeql

.github/labeler.yml
- some quick updates to the labeler config
=> ci(pr): update labeler config

.github/workflows/pr.yml
- fixes labeler when a pr comes from a fork
=> ci(pr): fix labeler with prs from forks

apps/web/pages/index.tsx
- just adding full stops to the end of sentences.
=> Fix punctuation

apps/web/components/Finished.tsx, apps/web/pages/account.tsx, apps/web/pages/auth/login.tsx, apps/web/pages/index.tsx, apps/web/pages/submissions/review.tsx, apps/web/pages/submissions/upload.tsx
=> fix(web): Spacing issues

apps/web/pages/index.tsx
- missing discord link on main page
=> fix(web): missing discord link

apps/web/pages/auth/login.tsx
- added checkbox for legal agreement on signup/login page.
- N/A
=> added checkbox on login/signup

apps/web/pages/submissions/upload.tsx, apps/web/server/trpc/router/gameplay.ts, apps/web/utils/zod/gameplay.ts, package.json, packages/database/package.json, packages/database/prisma/schema.prisma, yarn.lock
- prisma and prisma client updated from 4.8 -> 4.10.1
- added TRUSTED role to roles model.
- added Cheats model.
- added cheat dropdown and checks on site.
- added multiple cheat selection support 70a9113
NOTE: default cheat will always be NOCHEAT unless specified.
- Fixes #104, fixes #103
=> Some minor fixes, features, and depend updates

apps/web/next.config.js
- No longer ignore typescript builds
- only does half of #89
=> Remove typescript ignore from next config

docs/src/pages/en/getting-started.md
- Document prisma env file
- fixes #118
=> docs(prisma): env file

.github/dependabot.yml, .github/workflows/docs.yml, .github/workflows/pr.yml
- update dependabot pr limits
- always use node lts in ci
- gen prisma client before type checks
=> ci: general updates

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/pull_request_template.md
- feature request
- check if another fr for the same thing
- better project selection
- add code of conduct checkbox
- bug report
- better project selection in bug template
- use bash to render logs
- pr
- agree to code of conduct & read contributing guide
- fixes #97
=> ci: update templates

README.md, docs/src/config.ts, docs/src/pages/en/getting-started.md
- updated readme
- removed mentions of upstash
- updated picking work section
=> docs: update readme

apps/web/next.config.js
=> fix(discord): invite link

apps/web/Dockerfile, packages/database/Dockerfile
=> pin alpine version

packages/database/prisma/schema.prisma
=> prisma binary targets

apps/web/pages/api/auth/[...nextauth].ts
- sign in issue occured when an admin user logins
- N/A
---
=> fixed sign in issue

apps/web/pages/api/auth/[...nextauth].ts, package.json, yarn.lock
- fixes some possible provider issues with authentication
- N/A
---
=> (hopefully) fixed provider issues

apps/web/pages/api/auth/[...nextauth].ts, apps/web/pages/submissions/review.tsx, apps/web/pages/submissions/upload.tsx, apps/web/server/trpc/router/gameplay.ts
- disable ts frontend and backend checks / added bot protection on cf dash
- N/A
---
=> disable turnstile stuff for now

.github/workflows/release.yml, apps/web/Dockerfile
=> feat(web): add turnstile site key on docker build

apps/web/pages/account.tsx, apps/web/pages/api/auth/[...nextauth].ts, apps/web/pages/dash/gameplay.tsx, apps/web/pages/dash/users.tsx, apps/web/pages/submissions/review.tsx
=> style(web): fix eslint errors

apps/web/components/account/DeleteAccModal.tsx
Fixes a bug where it would infinitly load after deleting an account
- Adds a loading spinner to the delete account confirmation modal when the button is pressed. Then redirects to the main page.
- N/A
---
=> fix(web): infinite loading on account deletion

apps/web/pages/index.tsx, docs/src/config.ts, docs/src/pages/en/faq.md
=> refactor(web): update wording on index

apps/web/pages/submissions/review.tsx, apps/web/pages/submissions/upload.tsx, apps/web/server/trpc/router/util.ts, apps/web/utils/helpers/apiHelper.ts
- add debug stuff to deploy to prod
---
=> add debug stuff for prod testing

apps/web/server/trpc/router/gameplay.ts, apps/web/server/trpc/router/util.ts
=> more debugging

apps/web/server/trpc/router/gameplay.ts
- log some specifics and fix possible culperit. (the error is right in the section I changed)
---
=> attempt another fix

apps/web/components/TurnstileWidget.tsx, apps/web/server/trpc/router/gameplay.ts, apps/web/server/trpc/router/util.ts
- removed some bad turnstile logic, fixed another issue.
- N/A
---
=> (hopefully) fixed turnstile

apps/web/server/trpc/router/gameplay.ts
- remove token call on first endpoint of review flow.
- N/A
---
=> remove checks on first endpoint from the flow

apps/web/components/TurnstileWidget.tsx, apps/web/package.json, apps/web/pages/submissions/review.tsx, apps/web/pages/submissions/upload.tsx, yarn.lock
- attempt at fixing ts bug
- N/A
---
=> fix attempt at review & ts bug

apps/web/components/TurnstileWidget.tsx
- ignore types cause they dont exist.
---
=> fix non-existent type

apps/web/components/TurnstileWidget.tsx, apps/web/pages/submissions/review.tsx
- Attempting to fix issue with ts token state and render methods that cause an issue on review page.
- N/A
---
=> Attempting ts fix (again)

apps/web/components/TurnstileWidget.tsx, apps/web/pages/auth/login.tsx, apps/web/pages/submissions/review.tsx
- enable google oauth and rollback previous broken commits.
- N/A
---
=> enable google oauth and rollback commits.

apps/web/pages/submissions/review.tsx, apps/web/pages/submissions/upload.tsx, apps/web/server/trpc/router/gameplay.ts, apps/web/utils/zod/gameplay.ts, packages/database/prisma/schema.prisma
- adds some more game options to the dropdown
- adds user stats to review page (request by a user in the discord and Rican approved)
-N/A
---
=> Feat suggestions

packages/database/package.json, packages/database/prisma/migrations/20230331214617_better_indexing/migration.sql, packages/database/prisma/schema.prisma, yarn.lock
We currently query a number of things in models that aren't indexed all the time, this fixes that issue. Also bumped prisma to fix an issue with cockroach migrations.
---
=> perf: improve queries on common items

docs/src/pages/en/getting-started.md
Added a few more lines of imformation to the getting started docs:
- How to run cockroachdb locally on windows
- How to start yarn workspace for individual modules
---
=> Added more info about running & Windows Database

docker-compose.test.yml, packages/database/Dockerfile, packages/database/entrypoint.sh
- Prisma migrate should fail on an error
n/a
---
=> fix(database): migrate should fail on errors

apps/web/next.config.js, apps/web/package.json, apps/web/pages/account.tsx, apps/web/pages/dash/gameplay.tsx, apps/web/pages/dash/status.tsx, apps/web/pages/dash/users.tsx, apps/web/server/trpc/context.ts, yarn.lock
- upgrade next auth
- upgrade nextjs
- n/a
---
=> build(web): upgrade next auth and nextjs

.github/release-drafter.yml
- mark dependabot prs as maintenance
- n/a
---
=> ci(drafter): mark dependabot prs as maintenance

apps/web/package.json, apps/web/pages/submissions/upload.tsx, yarn.lock
- Updated chakra-ui versions in apps/web/package.json to newest to fix builds failing
- Replaced experimental_spaceX with gap in submissions page to allow for newest chakra-ui
=> Fixed chakra dependency & failing build

.github/workflows/release.yml
Get all git history and and better version tagging
- Get all git history and and better version tagging
- n/a
---
=> ci(release): fix sentry release

.github/workflows/release.yml
=> ci(release): REALLY move to v1 formating

apps/web/next.config.js, apps/web/pages/submissions/review.tsx
- fixed issue described here: https://discord.com/channels/903349717323382814/1096839104139894936
=> Fixed Clip Review breaking on invalid user image

apps/web/server/trpc/router/gameplay.ts, packages/database/prisma/migrations/20230417221847_m4d17/migration.sql, packages/database/prisma/schema.prisma
- hopefully fixes or if not gives us more insight to what might be the issue with gameplay deletion on prod
-N/A
---
=> attempt to fix gameplay deletion errors

apps/web/server/trpc/trpc.ts
- fix possibility of errors & exploits in link retrieval api
---
=> Added header parsing & keychecking to link retrieval api

apps/web/next.config.js
- plausible has its sub-directory set incorrectly
- plausible isn't reporting traffic rn
---
=> fix(plausible): improper subdirectory

apps/web/next.config.js
- fix for plausible's proxy
n/a
---
=> fix(web): plausible use default proxy options

apps/web/package.json, apps/web/pages/api/[...trpc].ts, apps/web/pages/api/openapi.json.ts, apps/web/server/trpc/openapi.ts, apps/web/server/trpc/trpc.ts, yarn.lock
- I thought we weren't using open api...
- n/a
---
=> Revert: build(openapi): remove from web workspace

apps/web/next.config.js
- fix plausible proxy
- fixes #329 
---
=> fix(plausible): set custom domain

apps/web/components/TurnstileWidget.tsx
I typed the `Turnstile` ref with `TurnstileInstance`.
---
=> Type turnstile ref
