waldo-vision/waldo

.editorconfig
.prettierrc.js
.vscode/extensions.json
.vscode/settings.json
package.json

Highlights:
- `.editorconfig`
- recommended vscode extensions
- some "best practice" vscode settings

Some developer experiance related 

---

.github/ISSUE_TEMPLATE/config.yml

the issue reporter already mentions security vuln reporting
none

ci(github): remove double mention of security

---

apps/web/Dockerfile

- used the wrong path for static assets in the docker image

fix(web): static assets in container

---

apps/web/pages/account.tsx

Your are connected to a {name} account. => You are connected to a {name} account.
- Fixes a typo I noticed in the /account page of the website.
**Your** are connected to a {name} account. => **You** are connected to a {name} account.`
- [ x ] I have read the [Contributing Guide](https://docs.waldo.vision/en/getting-started/), and agree to follow the [Code of Conduct](https://docs.waldo.vision/legal/code-of-conduct/).

fix(web/account): account connected typo

---

apps/web/next.config.js
apps/web/pages/submissions/upload.tsx

- adds a nonce to the csp headers that cf can detect with cdn and inject
- N/A
---

add nonce to csp for cf turnstile

---

apps/web/components/BlacklistedModal.tsx

- Fixed the typo 'suspened' to 'suspended' in BlacklistedModal.tsx that was found by Big_Funky.

Fixed typo found by Big_Funky

---

apps/web/pages/dash/users.tsx
apps/web/styles/dash/Users.module.css

Blurs email addresses in the dashboard unless hovered to prevent accidental leaks of information
- Adds a feature where email addresses are blurred in the dashboard.
- Introduces a `styles` folder for custom CSS.
- N/A
---

feat(web/dashboard): blur email addresses in the dashboard

---

docs/src/pages/en/getting-started.md

This change resolves #192 by changing "Before you can started hacking away on waldo, you need to have the tools below to ensure everything works." to "Before you can start hacking away on waldo, you need to have the tools below to ensure everything works."
#192
- [X ] I have read the [Contributing Guide](https://docs.waldo.vision/en/getting-started/), and agree to follow the [Code of Conduct](https://docs.waldo.vision/legal/code-of-conduct/).

fixed typo: changed started to start

---

docs/src/pages/en/getting-started.md

- fixes getting started page in docs
- currently the getting started page styling is broken
---

docs: fix getting started page

---

packages/database/package.json
packages/database/prisma/migrations/20230401161319_a1d1/migration.sql
yarn.lock

- adds schema migrations (a1d1)
- bumps prisma versions to @4.12 (client, and prisma)
- N/A
---

bump prisma version; create new migration (a1d1)

---

.github/workflows/release.yml

- updated formatting of docker tags
- now `v1` instead of `1`
n/a
---

ci(release): v1 instead of 1 as docker tag

---

apps/web/pages/submissions/review.tsx

- add allowfullscreen tag to youtube embed on review page
- add minimal width for embed, to mitigate issues on wide screens (should not break mobile, since only minimal widht)
- Fixes this: [Big Monitor Issue](https://github.com/waldo-vision/waldo/issues/228)
---

Fullscreenable embed on rewiev page & wide monitor min width

---

apps/web/pages/index.tsx

- added open graph tags as requested by #99 
- this should produce better embeds when https://waldo.vision is shared on Discord etc.
- Issue #99 is not resolved with this, since only index page gets better embed (Idea: Share Buttons on site?)
- #99 
---

Added simple OpenGraph tags to main site for better embeds on link sharing

---

apps/web/pages/submissions/upload.tsx

- add forced game selection, by setting initial game to null
- if game is null on submission, error message is displayed
- null in select game list makes it display the "Select a game prompt"
- selectedGame is not read otherwise, so no weird null exceptions this time
- #229 
---

Added forced game selection for video submission

---

apps/web/.env.example
apps/web/README.md
docker-compose.yml
docs/src/pages/en/getting-started.md
packages/database/.env.example

- Updated `apps/web/README.md` to have up-to-date description of the monolith app.  See the new README [here](https://github.com/waldo-vision/waldo/tree/fix/update-web-docs/apps/web). Also updated the getting started instructions in the docs website.
- Made a couple of tweaks to `docker-compose.yml` to fix a couple of issues I ran into while starting the containers with SELinux enabled. 
- N/A
---

docs: update local dev server README

---

apps/web/pages/dash/gameplay.tsx

- After a gameplay clip has been deleted, the UI should query the list of clips from the backend again and the deleted one should disappear.
- [Admin / Mod cannot delete gameplay](https://github.com/waldo-vision/waldo/issues/245)
---

fix: refresh gameplay clips after deletion

---

apps/web/server/trpc/router/gameplay.ts

- remove a double import failing the build

Removed double import for sentry to fix failing build

---

apps/web/package.json
yarn.lock

- Downgrading our NextJS version to combat the `Cannot find module 'next/dist/compiled/jest-worker'` error until they push a fix. It appears [they are aware of the issue](https://github.com/vercel/next.js/issues/48173)
- #290
---

fix: downgrade nextjs version to 13.2.4

---

docs/src/pages/en/getting-started.md
package.json

- Added a shortcut for yarn that installs deps, updates db schema and pushes to database
- should make checking out branches easier: just run `yarn branch` when doing a git checkout
- Added to docs
---

Added yarn branch shortcut to fix branching version mismatches

---

apps/web/pages/account.tsx
apps/web/pages/portal/developers/apikeys.tsx

- Trusted Users can now create API keys
- API page link is not displayed anymore for normal users
- Fixes #314 
---

Removed API link for USER role in Account page & Trusted can now create API keys

---

apps/web/server/trpc/router/analysisApi.ts

- There was an API bug, where valid percentage was inverted 0% would return no valid videos and 100% would return all, due to an inverted comparison. That is now fixed
- The query for the votes queried all summed no votes over all videos while the yes votes only got queried on current video, which really screwed the percentages. That should be fixed now
---

Fix link api percentage limit inverted bug & Database vote query count error

---

apps/web/pages/submissions/review.tsx

Checking for a nonexistent image externally on the server side makes no sense, so we use the Chakra Image which pulls on client-side thereby preventing those image not found server errors. Also you can specify an alternate image, if the image is not found anymore, which is set to the default battle.net image. We should avoid using the react image, since I think it is meant for self-hosted images.
- Replace react server side image with Chakra client side checked image to prevent server error spam.
- [#330](https://github.com/waldo-vision/waldo/issues/330)
---

Replaced React image with Chakra image to fix server error
